// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjseS5nVxtXk1dOV3Je6LfULbTG6QqV4',
    appId: '1:787337126161:web:90e6e4e57372727a75ecb0',
    messagingSenderId: '787337126161',
    projectId: 'flash-ink-app',
    authDomain: 'flash-ink-app.firebaseapp.com',
    storageBucket: 'flash-ink-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsGVGpgyeDlEE_qFFrcirnd5ILKjIkBJY',
    appId: '1:787337126161:android:157fc6b67e162ac075ecb0',
    messagingSenderId: '787337126161',
    projectId: 'flash-ink-app',
    storageBucket: 'flash-ink-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvkjlQlMeteV2qroXCKGL00goZZHZn6Ys',
    appId: '1:787337126161:ios:6a98d61df244ad3075ecb0',
    messagingSenderId: '787337126161',
    projectId: 'flash-ink-app',
    storageBucket: 'flash-ink-app.firebasestorage.app',
    iosClientId: '787337126161-492cglfi7b9o6ambkelgahcsgmogopm3.apps.googleusercontent.com',
    iosBundleId: 'com.seejaye.flashInk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvkjlQlMeteV2qroXCKGL00goZZHZn6Ys',
    appId: '1:787337126161:ios:6a98d61df244ad3075ecb0',
    messagingSenderId: '787337126161',
    projectId: 'flash-ink-app',
    storageBucket: 'flash-ink-app.firebasestorage.app',
    iosClientId: '787337126161-492cglfi7b9o6ambkelgahcsgmogopm3.apps.googleusercontent.com',
    iosBundleId: 'com.seejaye.flashInk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqjseS5nVxtXk1dOV3Je6LfULbTG6QqV4',
    appId: '1:787337126161:web:ce60474b7574e30c75ecb0',
    messagingSenderId: '787337126161',
    projectId: 'flash-ink-app',
    authDomain: 'flash-ink-app.firebaseapp.com',
    storageBucket: 'flash-ink-app.firebasestorage.app',
  );
}
